### ISSUE TITLE
Quick start tutorial request

### ISSUE THREAD

**Issue by dentex** [gyulavoros/downloadmanager#1]
Hi,
is it possible to have some basic usage info?
Thanks.

**Comment by dentex** [comment]
LoL! noticed I already made this...
:)
ANy news?

**Comment by gyulavoros** [comment]
The project is no longer maintained, feel free to use as a base for any project, but if I would use it, probably I would rewrite from scratch and make use the tools and libraries that are now available.

**Comment by dentex** [comment]
Ok, I see. 
Thanks for sharing it.

Bye.
